### ISSUE TITLE
Mosha Mermelstein is missing

### ISSUE THREAD

**Issue by rspeeruchicago** [rspeeruchicago/Maot-Chitim#4]
Trace back to Act  Find where it dropped

**Comment by rspeeruchicago** [comment]
My notes say that I'm missing a Mosha Mermelstein, but I can't find it in act either.  I do have 5 other Mermelsteins, just no Mosha.  Please verify in act and send screen shot if you find it.

**Comment by Jstoliar** [comment]
If you have Marvin Mermelstein- it's Moshe. If you have 5 then it's him.  Did Eugene Zemsky show up?  I think you are good!

**Comment by rspeeruchicago** [comment]
We are all good with Marvin and Eugene.  Closing this item
